modules:
  arm_controller:
    node_name: "test_arm_controller_node"  # 这里必须和上面的可执行文件名一致
    watch_topic: "/arm/status"             # 测试节点发布的状态话题
    enabled: true
    auto_start: true
    auto_restart: true
    timeout_sec: 1.0

cmd_route:
  arm_control:
    topic: "/arm/control"                  # 测试节点订阅的控制话题
    msg_type: "Robotarmcontrol"